
package org.rdv.ui;

import org.rdv.DataViewer;
import javax.swing.ImageIcon;

public class RDVIcon {
  public static final ImageIcon cancel       ;
  public static final ImageIcon close        ;
  public static final ImageIcon closeAll     ;
  public static final ImageIcon refresh      ;
  public static final ImageIcon properties   ;
  public static final ImageIcon info         ;
  public static final ImageIcon time         ;
  public static final ImageIcon hidden       ;
  public static final ImageIcon rt           ;
  public static final ImageIcon go           ;
  public static final ImageIcon begin        ;
  public static final ImageIcon play         ;
  public static final ImageIcon pause        ;
  public static final ImageIcon end          ;
  public static final ImageIcon control      ;
  public static final ImageIcon filter       ;
  public static final ImageIcon channels     ;
  public static final ImageIcon closeChannel ;
  public static final ImageIcon audio        ;
  public static final ImageIcon audioPlay    ;
  public static final ImageIcon expandAll    ;
  public static final ImageIcon collapseAll  ;
  public static final ImageIcon importData   ;
  public static final ImageIcon exportData   ;
  public static final ImageIcon dropData     ;
  public static final ImageIcon server       ;
  public static final ImageIcon folder       ;
  public static final ImageIcon folderOpen   ;
  public static final ImageIcon folderUp     ;
  public static final ImageIcon data         ;
  public static final ImageIcon jpeg         ;
  public static final ImageIcon text         ;
  public static final ImageIcon file         ;
  public static final ImageIcon attach       ;
  public static final ImageIcon detach       ;
  public static final ImageIcon up           ;
  public static final ImageIcon down         ;
  public static final ImageIcon leftBound    ;
  public static final ImageIcon rightBound   ;
  public static final ImageIcon vertical     ;
  public static final ImageIcon horizontal   ;
  public static final ImageIcon tiled        ;
  public static final ImageIcon throbberAnim ;
  public static final ImageIcon throbber     ;
  public static final ImageIcon neesITandUB  ;
  public static final ImageIcon marker       ;
  public static final ImageIcon markerAnnotation     ;
  public static final ImageIcon markerStart          ;
  public static final ImageIcon markerStop           ;
  public static final ImageIcon roboticControlOpen   ;
  public static final ImageIcon roboticControlClose  ;
  public static final ImageIcon roboticControlHome   ;
  public static final ImageIcon roboticControlAuto   ;
  public static final ImageIcon roboticControlNear   ;
  public static final ImageIcon roboticControlFar    ;
  public static final ImageIcon roboticControlPlus   ;
  public static final ImageIcon roboticControlMinus  ;
  public static final ImageIcon roboticControlUp     ;
  public static final ImageIcon roboticControlDown   ;
  public static final ImageIcon roboticControlLeft   ;
  public static final ImageIcon roboticControlRight  ;
  public static final ImageIcon roboticControlIrisbarMedium  ;
  public static final ImageIcon roboticControlFocusbarMedium ;
  public static final ImageIcon roboticControlZoombarMedium  ;
  public static final ImageIcon roboticControlTiltbarMedium  ;
  public static final ImageIcon roboticControlPanbarMedium   ;
  
  static {
     cancel       = DataViewer.getIcon("icons/cancel.gif");
     close        = DataViewer.getIcon("icons/close.gif");
     closeAll     = DataViewer.getIcon("icons/closeall.gif");
     refresh      = DataViewer.getIcon("icons/refresh.gif");
     properties   = DataViewer.getIcon("icons/properties.gif");
     info         = DataViewer.getIcon("icons/info.gif");
     time         = DataViewer.getIcon("icons/time.gif");
     hidden       = DataViewer.getIcon("icons/hidden.gif");
     rt           = DataViewer.getIcon("icons/rt.gif");
     go           = DataViewer.getIcon("icons/go.gif");
     begin        = DataViewer.getIcon("icons/begin.gif");
     play         = DataViewer.getIcon("icons/play.gif");
     pause        = DataViewer.getIcon("icons/pause.gif");
     end          = DataViewer.getIcon("icons/end.gif");
     control      = DataViewer.getIcon("icons/control.gif");
     filter       = DataViewer.getIcon("icons/filter.gif");
     channels     = DataViewer.getIcon("icons/channels.gif");
     closeChannel = DataViewer.getIcon("icons/close_channel.gif");
     audio        = DataViewer.getIcon("icons/audio.gif");
     audioPlay    = DataViewer.getIcon("icons/audio_play.gif");
     expandAll    = DataViewer.getIcon("icons/expandall.gif");
     collapseAll  = DataViewer.getIcon("icons/collapseall.gif");
     importData   = DataViewer.getIcon("icons/import.gif");
     exportData   = DataViewer.getIcon("icons/export.gif");
     dropData     = DataViewer.getIcon("icons/drop_data.gif");
     server       = DataViewer.getIcon("icons/server.gif");
     folder       = DataViewer.getIcon("icons/folder.gif");
     folderOpen   = DataViewer.getIcon("icons/folder_open.gif");
     folderUp     = DataViewer.getIcon("icons/folder-up.gif");
     data         = DataViewer.getIcon("icons/data.gif");
     jpeg         = DataViewer.getIcon("icons/jpeg.gif");
     text         = DataViewer.getIcon("icons/text.gif");
     file         = DataViewer.getIcon("icons/file.gif");
     attach       = DataViewer.getIcon("icons/attach.gif");
     detach       = DataViewer.getIcon("icons/detach.gif");
     up           = DataViewer.getIcon("icons/up.gif");
     down         = DataViewer.getIcon("icons/down.gif");
     leftBound    = DataViewer.getIcon("icons/left_bound.gif");
     rightBound   = DataViewer.getIcon("icons/right_bound.gif");
     vertical     = DataViewer.getIcon("icons/vertical.gif");
     horizontal   = DataViewer.getIcon("icons/horizontal.gif");
     tiled        = DataViewer.getIcon("icons/tiled.gif");
     throbberAnim = DataViewer.getIcon("icons/throbber_anim.gif");
     throbber     = DataViewer.getIcon("icons/throbber.png");
     neesITandUB  = DataViewer.getIcon("icons/neesanditub.gif");
     marker       = DataViewer.getIcon("icons/marker.gif");
     markerAnnotation     = DataViewer.getIcon("icons/marker-annotation.gif");
     markerStart          = DataViewer.getIcon("icons/marker-start.gif");
     markerStop           = DataViewer.getIcon("icons/marker-stop.gif");
     roboticControlOpen   = DataViewer.getIcon("icons/ptz/robotic_control-open.gif");
     roboticControlClose  = DataViewer.getIcon("icons/ptz/robotic_control-close.gif");
     roboticControlHome   = DataViewer.getIcon("icons/ptz/robotic_control-home.gif");
     roboticControlAuto   = DataViewer.getIcon("icons/ptz/robotic_control-auto.gif");
     roboticControlNear   = DataViewer.getIcon("icons/ptz/robotic_control-near.gif");
     roboticControlFar    = DataViewer.getIcon("icons/ptz/robotic_control-far.gif");
     roboticControlPlus   = DataViewer.getIcon("icons/ptz/robotic_control-plus.gif");
     roboticControlMinus  = DataViewer.getIcon("icons/ptz/robotic_control-minus.gif");
     roboticControlUp     = DataViewer.getIcon("icons/ptz/robotic_control-up.gif");
     roboticControlDown   = DataViewer.getIcon("icons/ptz/robotic_control-down.gif");
     roboticControlLeft   = DataViewer.getIcon("icons/ptz/robotic_control-left.gif");
     roboticControlRight  = DataViewer.getIcon("icons/ptz/robotic_control-right.gif");
     roboticControlIrisbarMedium  = DataViewer.getIcon("icons/ptz/robotic_control-irisbar-medium.gif");
     roboticControlFocusbarMedium = DataViewer.getIcon("icons/ptz/robotic_control-focusbar-medium.gif");
     roboticControlZoombarMedium  = DataViewer.getIcon("icons/ptz/robotic_control-zoombar-medium.gif");
     roboticControlTiltbarMedium  = DataViewer.getIcon("icons/ptz/robotic_control-tiltbar-medium.gif");
     roboticControlPanbarMedium   = DataViewer.getIcon("icons/ptz/robotic_control-panbar-medium.gif");
  }
}
