
package org.rdv.stream;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

import junit.framework.TestCase;

public class StreamerTest extends TestCase {

  private static final String TEST_SHORT = "abc123";

  private static final String TEST_LONG = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae ipsum at diam adipiscing imperdiet. Pellentesque laoreet tincidunt ante, id faucibus magna bibendum at. Nam porta feugiat aliquet. Suspendisse at metus augue. Praesent nec aliquam felis. Nulla bibendum gravida tincidunt. Aliquam eget dolor neque, ut viverra sem. Cras at rhoncus justo.\n" + 
  		"\n" + 
  		"Curabitur sit amet neque elit. Fusce et erat quis lorem sagittis auctor non vitae lacus. Suspendisse suscipit lorem eget nunc tincidunt cursus. Vestibulum fermentum justo ac ante rhoncus convallis. Aenean eu leo neque, at lacinia massa. Nunc enim massa, volutpat ut porta a, malesuada a purus. Sed sed tempus velit. Suspendisse rhoncus dignissim urna id auctor. Maecenas ut sem lacus, vitae gravida massa. Integer nulla purus, tempus nec accumsan non, elementum nec nunc. Nulla pretium molestie tincidunt. In a odio ac leo adipiscing sollicitudin sit amet consequat est. Maecenas pharetra placerat dui at viverra.\n" + 
  		"\n" + 
  		"Vestibulum bibendum semper magna eu sagittis. Curabitur dui mauris, tincidunt id egestas sed, tincidunt in enim. Phasellus bibendum porta lorem, sed sodales purus tincidunt in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse suscipit, lectus ut consectetur lacinia, lacus ipsum tempor lectus, aliquam vehicula nulla magna quis elit. Nullam ut nibh ut leo congue accumsan ut at mi. Aenean nec ante ullamcorper dolor ultricies interdum. Nunc at porta felis. Ut sapien elit, dapibus et congue ac, auctor commodo dui. Etiam ac est est, non tempus tellus.\n" + 
  		"\n" + 
  		"Integer scelerisque elementum dapibus. Etiam est magna, consectetur vel condimentum eu, viverra sed libero. Etiam convallis vehicula ipsum at suscipit. Proin convallis fringilla dolor, sit amet fermentum neque vehicula in. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla ante massa, placerat eget lobortis nec, lacinia at leo. Fusce metus nunc, pretium in convallis sed, ornare eget lacus. Etiam id mi ac lorem rhoncus hendrerit sit amet ut dolor. Donec urna felis, sollicitudin fringilla convallis nec, auctor nec augue. Quisque sodales, elit ac luctus consectetur, nibh nulla eleifend tellus, et iaculis massa risus et metus. Donec porttitor faucibus arcu, a aliquam justo vulputate at. Sed pharetra felis ac massa congue mattis. Mauris at mauris eros, non aliquet lorem. Maecenas non ligula erat, vitae pharetra tellus. Mauris sollicitudin neque metus, ac convallis ante.\n" + 
  		"\n" + 
  		"Nullam auctor diam pulvinar tellus dapibus nec consequat nulla eleifend. Etiam bibendum mauris nec quam iaculis sit amet molestie odio sollicitudin. Morbi ornare orci vitae turpis gravida porttitor. Sed id tellus lectus, sit amet tincidunt ante. Nullam ullamcorper fringilla facilisis. Nulla facilisi. Donec orci odio, consectetur in dapibus et, rutrum in tellus. Sed quis metus non lectus semper fermentum. Morbi eu varius enim.\n" + 
  		"\n" + 
  		"Aliquam hendrerit, arcu porttitor lacinia blandit, nibh ligula placerat felis, vel scelerisque nulla nisi ut lorem. Aliquam erat volutpat. Aenean id ipsum sed sem fermentum pretium sed in leo. Vivamus elementum nisl eu libero ultricies viverra. Fusce ultricies augue bibendum elit lobortis scelerisque dictum lectus venenatis. Fusce tempor dui nec purus commodo facilisis. Nam nisl nisl, malesuada sed dictum eleifend, eleifend lacinia lacus. Sed non faucibus justo. Sed velit purus, lobortis et auctor vel, dapibus vitae tellus. Phasellus ornare, nibh tincidunt blandit pharetra, arcu sapien semper ligula, et porta purus leo a nunc. Cras vestibulum luctus leo, vitae faucibus sem dictum eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\n" + 
  		"\n" + 
  		"Cras tempor, nunc ac elementum porta, nunc libero luctus augue, non tincidunt tellus nisl at quam. Nunc vitae tortor vitae leo vulputate sollicitudin non ut est. Vivamus in mi risus, id imperdiet justo. Sed nec urna lorem, vitae scelerisque magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet lectus id neque dapibus vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam dapibus, sem sit amet pulvinar posuere, felis nunc tempor nulla, et euismod risus risus ac erat. Etiam commodo arcu at erat sodales lacinia.\n" + 
  		"\n" + 
  		"Cras turpis nulla, euismod nec egestas et, pellentesque ac mi. Praesent id libero sollicitudin ligula dapibus fermentum sit amet pharetra diam. Sed sed odio lectus, quis consectetur ligula. Quisque adipiscing euismod commodo. Sed auctor, neque sit amet hendrerit adipiscing, ante nisi varius eros, eget fringilla elit enim ut magna. Maecenas nulla erat, ultrices nec ultricies nec, placerat eget lacus. Mauris et libero tellus, at ultricies tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" + 
  		"\n" + 
  		"Cras tellus neque, placerat id consectetur vitae, condimentum sit amet nibh. Suspendisse potenti. Integer pretium lobortis odio ut fermentum. Praesent ut sollicitudin odio. Praesent imperdiet lorem nec odio venenatis faucibus. Sed eget orci non nisl tincidunt aliquam. Duis quis ornare arcu. Maecenas porttitor auctor libero nec congue. Morbi in accumsan ipsum. Cras porta, ligula eget aliquet commodo, lorem metus lobortis est, sed rutrum mauris tellus non arcu. In eget faucibus ligula. Morbi suscipit, lacus ac imperdiet fermentum, orci augue auctor urna, in iaculis quam felis fringilla massa. Pellentesque eu metus ut ipsum congue pulvinar et eu enim.\n" + 
  		"\n" + 
  		"Sed cursus nisi dapibus odio eleifend ac dignissim mauris iaculis. Suspendisse eu magna diam, facilisis dignissim odio. Aenean neque nibh, volutpat ut posuere id, mollis in neque. Duis quis neque urna, vel vestibulum ipsum. Nulla vestibulum tempus lacus ut ullamcorper. Mauris interdum diam a nulla placerat et rhoncus ipsum auctor. Mauris fermentum nisi nec nibh suscipit vitae convallis ligula dictum. Maecenas aliquam erat eget mi pharetra aliquet. Praesent elit justo, molestie at lobortis ut, tristique vel felis. Ut feugiat rutrum libero, sed tempus tortor viverra in.\n" + 
  		"\n" + 
  		"Ut egestas erat sed est varius varius quis eget diam. Mauris egestas lorem id sapien volutpat a tincidunt purus lobortis. Sed convallis, sem sit amet iaculis pulvinar, nisi elit vestibulum orci, ac suscipit lacus arcu sed magna. Integer pulvinar eleifend tincidunt. Sed at nibh nunc, id luctus tellus. Proin eu ipsum orci, ut vehicula ante. Fusce mi erat, vestibulum eu lobortis vitae, lacinia sed tellus.\n" + 
  		"\n" + 
  		"Mauris vitae nibh nibh, quis vehicula enim. Morbi sodales massa ut dolor tempor hendrerit. Etiam blandit, mauris id mattis laoreet, orci nisl lobortis justo, quis placerat justo nunc vehicula turpis. Suspendisse ultricies mollis sollicitudin. In urna velit, commodo sed feugiat at, blandit eget magna. Curabitur posuere semper nibh at volutpat. Proin urna ligula, mollis quis aliquam eu, ultricies ut elit. Duis ultrices venenatis mi tincidunt vulputate. Integer et nisi id tellus laoreet vulputate sed at augue. Phasellus sed sapien nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut massa lacus, non rhoncus turpis. Praesent quis est sed nunc vestibulum imperdiet tempor a massa. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" + 
  		"\n" + 
  		"Etiam ante augue, scelerisque et placerat et, porttitor vitae urna. Proin semper pellentesque nunc auctor interdum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam tempor cursus interdum. Vivamus dolor ligula, interdum sit amet auctor aliquam, mattis vel lectus. Ut et mi mauris. Fusce turpis orci, tempor vel bibendum quis, congue ut turpis. Aenean quis mi lacus, id lacinia nisl. Suspendisse sit amet quam eget diam posuere consectetur id ut felis.\n" + 
  		"\n" + 
  		"Integer nec enim risus. Vestibulum vel ipsum id est tincidunt bibendum eu sit amet lectus. Sed luctus vestibulum vehicula. Aenean elementum venenatis condimentum. Quisque lorem leo, condimentum a blandit vitae, dignissim in elit. Sed blandit augue eros, quis consequat diam. Donec vitae orci mollis ante mattis ornare. In pretium semper pellentesque.\n" + 
  		"\n" + 
  		"Sed ac ipsum nec magna facilisis dapibus. Maecenas ac quam a nisi posuere vulputate. Phasellus rutrum turpis non justo luctus non tempor metus pretium. Proin feugiat tristique interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Sed dictum sem sit amet quam placerat eu volutpat augue malesuada. Maecenas convallis metus molestie nibh imperdiet pretium. Suspendisse velit orci, feugiat eu suscipit eu, facilisis quis massa. Vivamus enim arcu, tempor quis egestas id, facilisis nec metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\n" + 
  		"\n" + 
  		"Mauris consequat rhoncus sapien, sit amet suscipit nulla gravida sit amet. Phasellus ut purus tellus. Integer in pretium leo. Quisque faucibus pharetra leo sit amet mollis. Aliquam risus purus, accumsan dapibus elementum sed, condimentum at neque. Phasellus eleifend commodo porta. Integer laoreet commodo elit eu euismod. Curabitur ut enim id felis varius malesuada et tempor dui. Sed ante diam, euismod et sollicitudin ut, bibendum a lectus. Mauris et mi lectus. Aliquam nisl est, mollis eget molestie sit amet, condimentum vitae tellus.\n" + 
  		"\n" + 
  		"Pellentesque convallis congue risus, sit amet consectetur mi posuere id. Pellentesque laoreet justo non nibh porta rhoncus. Donec eget risus massa, a venenatis ligula. Maecenas cursus rutrum sollicitudin. Cras gravida venenatis diam, vitae imperdiet mauris adipiscing condimentum. Nam sit amet ligula quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent hendrerit, nulla at fringilla hendrerit, augue arcu suscipit mauris, vitae porttitor sem orci vel velit.\n" + 
  		"\n" + 
  		"Ut in tristique risus. Phasellus id arcu lorem. Fusce in nulla tellus. Maecenas pellentesque orci vel nulla porttitor id interdum quam hendrerit. Aliquam erat volutpat. Sed sit amet tempor diam. Mauris dignissim enim id nibh ornare congue. Sed ut diam leo. Nullam quam sapien, tempor non euismod ac, ultricies in urna. In ut lacus lectus, et tempor diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce rhoncus malesuada neque, dignissim convallis orci aliquam nec.\n" + 
  		"\n" + 
  		"Sed pellentesque nulla eget tellus adipiscing viverra pulvinar mauris malesuada. Etiam ultricies, purus et fringilla malesuada, turpis velit semper velit, a bibendum ipsum dui in tellus. Proin in mauris enim. Maecenas eleifend diam et sem rutrum nec tempus risus elementum. Sed euismod tristique orci, at posuere metus volutpat sed. Aenean blandit dui velit, at pulvinar nisi. Nam tellus lacus, mattis tincidunt placerat nec, pharetra vitae elit. In hac habitasse platea dictumst. Nunc pulvinar, sapien ut egestas eleifend, ipsum risus luctus nisi, quis porta leo mauris in velit. Vivamus at nibh ut turpis tempus dignissim. Donec varius lectus non libero dictum mollis molestie purus rutrum. Curabitur aliquam nisi non augue sollicitudin sit amet hendrerit lectus auctor.\n" + 
  		"\n" + 
  		"Praesent feugiat commodo dui, sit amet vehicula tellus auctor ut. Suspendisse ligula sem, molestie sit amet varius vel, semper nec mi. Cras pretium euismod cursus. Nullam lacinia, risus consequat commodo venenatis, turpis dolor eleifend quam, sit amet suscipit tortor metus eu nulla. Aliquam nunc sapien, bibendum non consequat non, semper vitae nisl. Maecenas vel dui sed nisl euismod commodo. Aliquam vel quam a nisl posuere semper ut nec odio. Phasellus lorem enim, placerat egestas hendrerit vitae, consequat a mauris. Praesent quis ante sed eros euismod mattis ut eget erat. Ut a sagittis nibh.\n" + 
  		"\n" + 
  		"Vivamus vel ullamcorper augue. Aenean ac eros nec massa scelerisque volutpat. Mauris sed odio eu ligula adipiscing dictum. Aenean at ipsum dolor, a commodo velit. Nunc malesuada eros vitae turpis imperdiet nec mollis lectus tristique. Mauris at metus tortor, dictum porttitor ipsum. Curabitur aliquam tincidunt enim quis porttitor. Suspendisse scelerisque justo at est sodales euismod.\n" + 
  		"\n" + 
  		"Integer dictum dui at purus interdum auctor. Phasellus massa magna, volutpat non varius ac, ornare at dui. Phasellus scelerisque tellus gravida nisl euismod interdum. Curabitur vitae mi ut ipsum tristique pretium. Vestibulum consequat massa nec tellus dignissim luctus. Vestibulum non turpis lorem, id tincidunt nunc. Vestibulum aliquam euismod erat, nec egestas purus laoreet eleifend. In et tellus felis, a tincidunt velit. Proin eget magna nulla, non malesuada urna. Cras nunc justo, bibendum et aliquet eget, eleifend a tortor. Nunc ac gravida mi. Cras tellus felis, vehicula sed tincidunt a, pulvinar nec nibh. Donec metus diam, dignissim vel aliquam a, faucibus sit amet purus. Phasellus enim leo, dapibus sit amet tristique nec, sollicitudin at nisi. Aliquam erat volutpat.\n" + 
  		"\n" + 
  		"Curabitur augue metus, luctus in auctor vitae, consectetur nec sapien. Curabitur massa libero, lobortis at venenatis id, tincidunt id felis. Aenean et mi est. Quisque pretium dapibus porta. Nulla ut adipiscing est. Aenean luctus posuere magna ac gravida. Morbi vestibulum libero non leo euismod vitae pretium mi hendrerit. Maecenas non rutrum purus. Nullam hendrerit sapien at odio tempus facilisis. Donec porttitor velit pretium justo interdum ornare et eu magna. Ut sed varius justo.\n" + 
  		"\n" + 
  		"Integer tempus, arcu et fringilla ultricies, tortor turpis sagittis urna, et sodales metus erat id dui. Nam tellus metus, interdum eleifend tempor eu, scelerisque non purus. Phasellus a turpis leo, vel porta orci. Quisque sit amet elit leo, sit amet interdum urna. Aenean vel felis mi, at suscipit ipsum. Maecenas elementum vulputate dolor, ac ultrices turpis adipiscing vitae. Donec fringilla suscipit elit id pellentesque. Quisque id lorem ac turpis vestibulum porttitor. Ut mi ligula, luctus quis feugiat vitae, sagittis ut tellus. Duis ipsum mauris, cursus nec tristique non, euismod eget ante. Pellentesque blandit interdum nunc sit amet consequat. Donec urna ipsum, sagittis et accumsan sed, bibendum eget ligula. Nulla ut ante et odio fermentum vehicula sit amet nec ante. Curabitur ac arcu a felis molestie accumsan. Sed sagittis, sapien in mattis porta, leo nulla semper est, at lobortis metus neque et nibh. Aenean sit amet tincidunt metus.\n" + 
  		"\n" + 
  		"Cras est diam, gravida mollis egestas et, pellentesque id ante. Sed sed neque vel libero eleifend hendrerit at quis odio. Suspendisse risus neque, accumsan quis gravida ut, iaculis sed velit. Phasellus commodo erat id elit dapibus tristique. In fermentum purus lectus, sed varius erat. In at mattis quam. Sed tincidunt interdum rhoncus. In venenatis, dui vitae viverra placerat, velit sapien rutrum metus, non accumsan neque erat at velit. Sed at rutrum lacus. Cras sapien erat, venenatis id mollis eget, sagittis ut lorem. Sed orci enim, tincidunt a commodo id, convallis eu dui.\n" + 
  		"\n" + 
  		"Suspendisse vel turpis justo, vel vehicula tellus. Quisque elit ipsum, malesuada sit amet aliquet sit amet, suscipit in elit. Nunc rhoncus mauris sed metus ultricies in rhoncus lacus dapibus. Nullam scelerisque ligula quis odio mollis pulvinar. Phasellus eros erat, ornare at gravida id, scelerisque in odio. Integer molestie sapien in enim tristique a gravida nunc posuere. Donec eu dapibus urna. Proin porta placerat quam vitae tristique. Sed tincidunt hendrerit justo, vel suscipit dui ullamcorper sit amet.\n" + 
  		"\n" + 
  		"Vivamus augue turpis, gravida quis vehicula sit amet, luctus sit amet elit. Fusce gravida, nulla sit amet tincidunt ornare, metus nunc bibendum nibh, ut suscipit elit neque sagittis leo. Mauris vitae vestibulum massa. Etiam quis leo augue, sit amet imperdiet tellus. Suspendisse nulla erat, convallis sit amet porta a, congue ac nisi. Aliquam erat volutpat. In vitae purus est. Integer rutrum odio nec nunc interdum suscipit.\n" + 
  		"\n" + 
  		"Duis vestibulum, diam nec convallis semper, urna dolor elementum tellus, et feugiat mi tellus sit amet dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam rhoncus dolor nec massa lacinia egestas. Phasellus vel dolor vel nisl porta tristique. Curabitur a dictum purus. Sed rhoncus nisi aliquam ipsum rhoncus tincidunt semper ante sodales. Morbi ullamcorper pellentesque odio, in pulvinar nulla fringilla sit amet. In sed posuere massa. Nam ultricies blandit eros, a pellentesque justo volutpat ut. Quisque elit nulla, mollis sit amet viverra nec, aliquam nec turpis. Sed hendrerit tristique turpis fermentum ultricies. Morbi diam nunc, pharetra ut adipiscing vitae, auctor in ligula. Morbi congue ultricies purus non suscipit. Maecenas fermentum tincidunt orci, at sollicitudin libero porttitor vel. Vivamus iaculis feugiat arcu, et pulvinar ante pharetra at.\n" + 
  		"\n" + 
  		"Proin tellus libero, gravida eu euismod ut, faucibus sit amet mauris. Cras lorem libero, fringilla sit amet pulvinar eu, sodales vitae dui. Fusce ornare dignissim risus ac semper. Mauris ligula quam, tincidunt a condimentum eget, vulputate nec leo. Nam aliquam adipiscing est, sed laoreet nulla ullamcorper vel. Integer vulputate, velit quis lobortis faucibus, augue eros volutpat quam, eget mattis diam nulla sit amet libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n" + 
  		"\n" + 
  		"Mauris hendrerit, nunc vel lacinia tempor, libero velit volutpat urna, ut condimentum orci ligula ut dolor. Phasellus pretium pretium fermentum. Suspendisse varius facilisis arcu, vitae luctus sem dapibus in. Quisque venenatis varius semper. Cras tempor, felis a pulvinar rhoncus, odio dolor sollicitudin orci, nec placerat orci ante eu urna. Ut ut nunc nisi, sit amet gravida neque. Maecenas faucibus, dui id molestie vehicula, mi eros placerat lacus, ut dapibus ante urna at diam.\n" + 
  		"\n" + 
  		"Etiam bibendum convallis accumsan. Quisque sit amet nibh ut nibh laoreet sagittis. Donec tincidunt ullamcorper erat, dignissim auctor risus imperdiet vestibulum. Integer turpis augue, tristique id varius viverra, auctor quis ligula. Nam fringilla, dui sed malesuada malesuada, nunc nunc euismod urna, sit amet fringilla diam dolor faucibus lacus. Fusce arcu enim, feugiat a consectetur vitae, placerat ut urna. Donec fermentum nisl ipsum, a tempus dui. Donec quis augue ac orci porta accumsan ac nec erat. Suspendisse potenti. Quisque ultricies bibendum erat, ut faucibus nunc congue a. Nunc ipsum enim, sollicitudin eu rutrum fermentum, tincidunt quis felis.\n" + 
  		"\n" + 
  		"Nunc ullamcorper malesuada accumsan. Aenean lorem dolor, porttitor eu scelerisque a, lobortis vitae nibh. Cras auctor sollicitudin arcu ac sagittis. In eu mi lectus, id dictum tortor. Maecenas nec lectus justo, vitae volutpat diam. Vivamus sed erat velit, a elementum enim. Fusce facilisis diam eget orci posuere id ornare sem varius. Suspendisse elit justo, dictum sit amet vulputate a, pulvinar vel nunc. Sed semper, lacus vitae ultrices aliquet, felis ante vehicula risus, venenatis ornare justo lectus et dolor. Proin et ipsum leo, id fringilla dolor.\n" + 
  		"\n" + 
  		"Nunc ut neque mauris. Sed interdum dolor id arcu consequat eu pharetra felis rhoncus. Nulla semper gravida accumsan. Nullam fermentum nunc at elit fermentum in suscipit metus rutrum. Phasellus vitae quam et justo mattis dignissim sed ut magna. Aenean hendrerit semper nunc a vehicula. Donec feugiat placerat tincidunt. Morbi interdum molestie lobortis. Curabitur porta erat eu lectus pretium porta. Pellentesque varius lectus vitae mi varius faucibus. Aenean tempus venenatis congue. Praesent molestie hendrerit neque, ut malesuada neque posuere vel. Pellentesque vel urna lacus, id fringilla mauris. Suspendisse sodales mauris eget ante mattis tempus. Aliquam ut lorem non nisi faucibus ultrices tempor non augue.\n" + 
  		"\n" + 
  		"Sed vitae lectus nunc, vehicula rutrum odio. Maecenas id massa et ipsum ullamcorper scelerisque quis eget ante. Praesent ac erat semper erat vestibulum imperdiet. Morbi interdum porttitor arcu, ac luctus dui aliquet at. Maecenas eleifend sem sed ante commodo posuere. Integer ut nulla ut elit mollis ultrices. Nulla facilisi. Nam placerat volutpat nisl eu accumsan. Suspendisse ornare massa ac lacus placerat lobortis. Donec volutpat tristique urna eget porta. Ut vel lacus erat. Duis purus est, dictum quis faucibus quis, suscipit tempus dolor.\n" + 
  		"\n" + 
  		"Aenean eget orci ac neque ultrices pretium sed eu velit. Morbi luctus nisl sit amet nulla hendrerit quis imperdiet lorem ullamcorper. Donec imperdiet enim eu nibh blandit at ultrices justo volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent metus nunc, semper sed faucibus eget, pellentesque tincidunt massa. Donec volutpat ornare fermentum. Nulla nunc orci, placerat sit amet convallis a, interdum ultricies lacus. Praesent hendrerit aliquet arcu vel dictum. Cras et leo est. Curabitur venenatis, justo at fringilla interdum, leo lacus faucibus elit, eu porttitor augue massa a purus.\n" + 
  		"\n" + 
  		"Sed ac quam eget purus blandit auctor. Nam sed orci elit, et gravida quam. Curabitur hendrerit felis lacus, non adipiscing ipsum. Ut dignissim blandit dolor, eu suscipit nibh aliquam non. Aliquam scelerisque diam nec nulla rhoncus euismod. Donec pulvinar ante sit amet sapien dignissim sit amet vestibulum lorem tincidunt. Praesent vel mi et neque lacinia lacinia pulvinar ut neque. In sagittis rhoncus lorem, sit amet fermentum eros bibendum sagittis. Duis in interdum massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam et erat est. Phasellus justo neque, feugiat nec dapibus non, porta vel augue. Donec sit amet lacus eget nunc accumsan hendrerit. Vivamus blandit ornare lobortis. Suspendisse tincidunt ullamcorper purus sit amet hendrerit. Aliquam volutpat blandit fermentum.\n" + 
  		"\n" + 
  		"Nulla facilisi. Ut venenatis facilisis sapien, eu hendrerit diam dictum semper. Cras at neque vel velit interdum tincidunt eu quis enim. Morbi fringilla ullamcorper enim sit amet tempus. Proin sit amet arcu nunc. Donec rhoncus semper pellentesque. Etiam pellentesque, lectus eget fermentum aliquet, diam libero ullamcorper ligula, non fermentum nisi enim vitae nisi. Aliquam id orci sit amet neque commodo facilisis. Quisque pellentesque est dolor.\n" + 
  		"\n" + 
  		"Curabitur placerat urna vel est adipiscing sit amet gravida mauris condimentum. Duis scelerisque purus convallis ligula pulvinar euismod. Integer consequat elit id purus rutrum vel laoreet lectus bibendum. Etiam quis blandit lacus. In sodales enim eu odio semper consectetur. Vestibulum lacinia risus mauris. Ut pellentesque lorem eu nibh ornare adipiscing. Duis eget erat arcu. Cras metus dui, suscipit id pellentesque sed, mattis at tortor. Duis urna purus, fringilla sed rutrum in, interdum a dui.\n" + 
  		"\n" + 
  		"Mauris eu lectus orci, a sagittis mauris. Suspendisse potenti. Vestibulum pellentesque auctor quam, in ullamcorper enim varius in. Nulla facilisi. Cras ante lacus, scelerisque et dignissim sit amet, volutpat non ligula. Praesent dictum facilisis nulla, in gravida libero blandit in. Morbi egestas suscipit nibh, at pharetra purus consequat non. Ut eleifend ultrices libero ut condimentum. Aenean nunc erat, faucibus eget euismod nec, euismod a lorem. Morbi nec convallis orci. Cras sed augue lacus. Curabitur euismod, lorem vel consectetur ultricies, elit diam ullamcorper mauris, et tincidunt purus elit ac enim.\n" + 
  		"\n" + 
  		"Vivamus aliquet libero nisi. Donec lacinia hendrerit venenatis. Nulla molestie condimentum tellus, ornare lacinia risus porttitor sed. Donec gravida ultrices leo tristique vestibulum. Suspendisse vel ultricies leo. Etiam ullamcorper purus sed nunc tincidunt sit amet ultricies eros aliquam. Nullam et libero sit amet quam molestie fermentum eu sed purus. Duis vel augue sit amet neque sollicitudin ultricies nec a magna. Vivamus facilisis gravida metus non eleifend. Proin elit nibh, facilisis vitae rhoncus ut, pellentesque at nunc. Praesent risus orci, adipiscing ac accumsan faucibus, placerat nec risus.\n" + 
  		"\n" + 
  		"Quisque non nibh augue. Etiam volutpat, tortor et porttitor posuere, nibh lacus volutpat massa, id tempor sapien nunc at orci. Sed posuere arcu in mi convallis in pharetra ante ultricies. Aliquam rutrum leo eu risus vulputate pulvinar sit amet sit amet libero. Nullam laoreet, risus id fringilla posuere, arcu felis malesuada leo, vitae consectetur velit neque eget nisi. Nam vitae turpis diam, sed lobortis ipsum. Phasellus adipiscing massa et sem porttitor pellentesque. Sed varius libero libero. Proin velit justo, rutrum eget dapibus at, cursus sed odio. Morbi id pulvinar mauris. Vivamus ac accumsan diam. Duis porta, enim quis vehicula aliquet, ligula urna rutrum massa, sed bibendum ipsum lorem id risus.\n" + 
  		"\n" + 
  		"Curabitur leo leo, ullamcorper a gravida vel, malesuada et lectus. Sed porttitor elementum lacinia. Maecenas consequat volutpat metus nec mollis. Integer et leo ante, ut pellentesque justo. Nam pharetra, elit a lacinia tincidunt, tortor purus ultricies sem, vel ultricies erat leo sit amet mi. In vitae tincidunt ante. Pellentesque condimentum velit magna.\n" + 
  		"\n" + 
  		"Nullam nisi augue, vehicula in tincidunt a, scelerisque et sem. Praesent mauris enim, facilisis nec porta eget, laoreet a erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed lacus sem, facilisis a semper in, adipiscing ut massa. Proin iaculis, enim quis feugiat egestas, lorem massa feugiat est, in lacinia justo sem vel ante. Praesent eget lacus ut quam hendrerit bibendum id vel purus. Fusce quis sem nunc. Praesent nunc enim, molestie quis fringilla sit amet, pretium vitae dolor. Donec ut lacus mi. Aenean leo massa, consequat id scelerisque a, egestas et turpis. Quisque eleifend lacus eu enim aliquet id ultricies velit placerat. Maecenas at vulputate erat. Vestibulum vel ipsum nisi.\n" + 
  		"\n" + 
  		"Ut et mauris vitae arcu sollicitudin fringilla. Nullam euismod luctus ultricies. Maecenas a enim urna. Suspendisse vestibulum ipsum non dolor vehicula et vehicula orci malesuada. Aliquam ipsum quam, interdum in ornare at, adipiscing ac leo. Pellentesque ut purus felis. Phasellus orci augue, rhoncus ut condimentum iaculis, ultricies id mauris. Vivamus nec neque metus, vel lobortis orci. Ut id magna non orci tempor posuere. Cras consectetur imperdiet bibendum. Ut non quam in purus lacinia congue.\n" + 
  		"\n" + 
  		"Nam luctus tristique pellentesque. Sed ut urna rhoncus quam imperdiet elementum sed porttitor lacus. Nunc nec turpis sem, a cursus dolor. Donec mollis nisl aliquam diam viverra pulvinar. Etiam augue orci, pellentesque eu luctus ac, pulvinar eget nisi. Aenean lobortis, ligula sit amet tincidunt consequat, nunc sem pretium elit, a rutrum ligula massa et elit. Nulla sed diam ac lectus venenatis tincidunt. Aliquam erat volutpat. Nunc egestas, ligula id gravida posuere, odio diam semper velit, in iaculis nisi eros at velit. Vestibulum pretium egestas tellus. Suspendisse potenti. Nullam nec tortor nibh, quis semper turpis. In convallis, libero at convallis tristique, nulla dui gravida felis, vel eleifend lorem dui non sem.\n" + 
  		"\n" + 
  		"Etiam et nisl nisi, et feugiat sem. Aenean at lorem velit, venenatis auctor urna. Curabitur id velit quam, eu luctus quam. Phasellus at dui id eros placerat bibendum. Fusce dictum arcu ut mi lacinia ut tempor orci sagittis. Proin sit amet turpis ultrices leo convallis venenatis a a massa. Pellentesque ut accumsan libero.\n" + 
  		"\n" + 
  		"Proin interdum interdum iaculis. Nunc ultrices odio id velit interdum convallis. Nullam euismod, massa et tempor vulputate, velit felis imperdiet dolor, quis convallis velit enim non sem. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed et leo nisl. Pellentesque eu mauris est, vitae semper sapien. Fusce nibh arcu, dignissim eget consequat eget, dignissim non augue. Suspendisse id risus eros, eu dapibus dui.\n" + 
  		"\n" + 
  		"Integer auctor rhoncus urna, nec tempor nibh pulvinar eget. Integer massa orci, imperdiet a interdum at, posuere non nunc. Nam tempus nisl id libero blandit eget vehicula erat varius. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur venenatis lorem vel metus vulputate non consectetur odio egestas. Aenean facilisis augue non augue fermentum fringilla. Praesent eros nulla, molestie nec luctus id, rutrum et massa. Ut blandit velit accumsan justo tempus luctus.\n" + 
  		"\n" + 
  		"Suspendisse ornare aliquet elit, eu ullamcorper erat rutrum id. Maecenas in consectetur erat. Cras at convallis velit. Duis luctus sollicitudin facilisis. Aenean mattis laoreet ornare. Nullam sagittis arcu sem, sit amet lobortis augue. Fusce a velit ligula. Cras urna lacus, consectetur eu accumsan sed, fermentum non nisl. Proin molestie blandit orci eu mollis. Phasellus posuere, metus eget pharetra faucibus, dolor augue viverra nunc, a fringilla orci risus non nisl. Phasellus eu neque sit amet tellus vestibulum porttitor a nec lorem. Vestibulum tempor tristique nulla, sed laoreet arcu euismod ac. Duis non mollis ipsum. Aliquam dignissim fringilla semper. In sed arcu odio. Sed egestas malesuada nunc ac tincidunt.\n" + 
  		"\n" + 
  		"Morbi felis ligula, varius eget tristique vitae, imperdiet et arcu. Ut sagittis enim vel massa imperdiet vulputate aliquam mi egestas. Fusce a enim dolor. Curabitur justo mi, eleifend et aliquam eu, sagittis nec nulla. Integer a nulla orci. Curabitur ac leo scelerisque nisl cursus adipiscing. Mauris gravida, purus a faucibus bibendum, ipsum felis tempor risus, ut luctus elit lacus nec tortor. Praesent eget mauris eget orci volutpat lobortis. Sed dignissim malesuada elit, vel imperdiet orci lacinia et. Quisque arcu magna, mollis vitae iaculis in, mollis sed elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque at ante sed magna semper luctus eu quis massa. Nam vehicula bibendum turpis, a mattis purus suscipit vitae.\n" + 
  		"\n" + 
  		"Donec consectetur dignissim commodo. Praesent egestas aliquam sapien, vitae feugiat magna interdum rhoncus. Pellentesque congue congue sollicitudin. Nam luctus vulputate nisi quis ornare. In hac habitasse platea dictumst. Sed nibh elit, viverra a eleifend scelerisque, faucibus at justo. Quisque orci nibh, convallis ut cursus quis, adipiscing vel lacus.\n" + 
  		"\n" + 
  		"Integer dignissim molestie turpis mollis viverra. Proin dignissim elementum mollis. Integer molestie varius bibendum. Nulla orci neque, imperdiet eu faucibus ut, varius vel odio. Fusce ipsum dolor, malesuada eget sollicitudin eget, dignissim nec quam. Suspendisse sed dui tellus. Praesent sed elit ut eros ultrices scelerisque eu a ante. Aenean in nibh justo, non vestibulum sem. Sed placerat bibendum nisi sed convallis. Cras dignissim, tellus quis ullamcorper egestas, lectus metus varius libero, nec aliquet elit nisi fringilla velit. Sed ipsum risus, facilisis sit amet varius vitae, egestas ac purus. Vivamus egestas ligula eget est pulvinar ut bibendum dui adipiscing. Duis faucibus tempus nulla, et tempor turpis molestie id.\n" + 
  		"\n" + 
  		"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum quis augue nisi, non porttitor massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus accumsan magna vitae ipsum feugiat lobortis. Donec varius massa a sem convallis in hendrerit est faucibus. In vitae tempus lacus. Sed molestie lorem quis diam suscipit posuere. Pellentesque luctus mattis sagittis. Nullam ullamcorper felis vitae enim feugiat adipiscing. Sed dapibus mattis feugiat. Curabitur et erat turpis, nec auctor ante. Praesent gravida nunc dictum lacus faucibus laoreet. Sed interdum posuere molestie. Maecenas ultricies, lorem non aliquet mattis, massa justo pharetra orci, a scelerisque tortor mauris a nisi. Nam in diam erat, in venenatis nisi.\n" + 
  		"\n" + 
  		"Phasellus scelerisque rhoncus sodales. Nam dignissim volutpat viverra. Sed non enim id nunc tincidunt faucibus et a arcu. Suspendisse ut lorem ut magna suscipit auctor a in purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur facilisis iaculis mi vel congue. Cras sit amet purus a quam feugiat convallis quis nec est. Etiam in ipsum erat, quis ornare nulla. Nulla tincidunt tellus imperdiet neque convallis id tincidunt turpis blandit. In sed tortor dui. Maecenas ut dui metus.\n" + 
  		"\n" + 
  		"Integer ante elit, gravida non sollicitudin sed, hendrerit at nunc. Sed at lacus arcu. Suspendisse rutrum, metus et sollicitudin gravida, tellus justo aliquam massa, eu suscipit quam felis ut urna. Donec eu lorem eu mi ullamcorper porttitor. Praesent id nulla at est consequat tempus. Curabitur lacinia urna sed metus vestibulum luctus. Etiam volutpat, dolor vel vehicula fermentum, nisi nisl placerat enim, id lacinia velit nisl aliquet mi. Ut malesuada, tellus quis mollis semper, sem leo molestie felis, ultricies faucibus diam ligula at quam. Nulla tellus eros, fermentum vel feugiat non, placerat vitae dui. Curabitur accumsan est sit amet mauris sollicitudin pellentesque.\n" + 
  		"\n" + 
  		"Mauris sed nunc ligula, in hendrerit ante. Nulla pulvinar, magna vitae pretium laoreet, sapien odio dignissim nulla, sit amet luctus sem nisl vel quam. Ut elementum commodo nibh vitae pellentesque. Aliquam vitae mattis justo. Donec vitae libero lorem. Nullam nec enim et nunc ornare consectetur vel sit amet enim. Phasellus consectetur, velit vel accumsan interdum, libero augue tincidunt lacus, quis iaculis sapien mi vitae sem.\n" + 
  		"\n" + 
  		"Sed eros ante, aliquet id dapibus eget, interdum et enim. Nullam tellus leo, cursus eu sodales sed, tincidunt non enim. Pellentesque consequat, quam ac mollis fringilla, nunc risus cursus massa, in ultrices lorem justo a tortor. Aenean ut dolor libero. Donec tellus augue, tristique ut luctus eu, porta in turpis. Ut urna est, mattis quis egestas eget, luctus id metus. Curabitur ut dolor nec metus fermentum venenatis eget sed ipsum. Sed ligula massa, sollicitudin id ornare vitae, placerat vitae ante.\n" + 
  		"\n" + 
  		"Phasellus volutpat adipiscing sagittis. Integer non ornare purus. Phasellus dapibus mi id turpis tempor convallis. Mauris aliquam lacus nec leo eleifend molestie. Vivamus dictum enim nec quam pretium non pharetra odio lobortis. Nullam fringilla dapibus metus et mattis. Nunc luctus elit non nisl auctor eget congue orci eleifend. Ut in neque nulla, sit amet ornare est. Morbi nec mi ac nisl tincidunt mattis ut vitae urna. Quisque commodo pulvinar sem sed scelerisque. Nulla enim purus, convallis quis porttitor nec, consectetur eget diam. Nullam aliquet turpis quis leo pulvinar commodo.\n" + 
  		"\n" + 
  		"Phasellus viverra volutpat quam ac facilisis. Fusce et metus vel tellus eleifend rutrum non nec elit. Curabitur egestas laoreet tristique. Praesent commodo tincidunt ipsum non adipiscing. Praesent volutpat, libero ut scelerisque lacinia, ipsum est viverra arcu, a bibendum purus risus at purus. Proin venenatis adipiscing nisi, non eleifend libero iaculis id. Nulla mollis orci eu risus auctor eleifend. In tempus tincidunt nulla, a facilisis ipsum fringilla ac. Suspendisse ultrices pharetra nibh, porta iaculis erat pretium sit amet. Sed ante neque, vestibulum ullamcorper porttitor quis, gravida quis nibh. Nunc sed sem non neque pretium tincidunt vel vel sapien. Aliquam mi nisl, vulputate sed egestas ac, mollis sed ligula.\n" + 
  		"\n" + 
  		"Nunc imperdiet elementum est vel vehicula. Donec sapien tortor, pulvinar nec sollicitudin nec, auctor blandit est. Aliquam eget sodales nisl. Nulla facilisis molestie imperdiet. Mauris pulvinar, dolor sit amet mattis aliquet, velit lacus mattis elit, at placerat magna purus vitae nisi. Integer scelerisque dolor eu erat ullamcorper eleifend. Nunc non ante vitae enim bibendum semper. Nunc sed dui sed nibh gravida sodales.\n" + 
  		"\n" + 
  		"Vivamus non tempor nibh. Donec sed dui mattis diam feugiat vestibulum eu egestas libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi et urna diam. Pellentesque convallis ante sed leo porta suscipit pulvinar augue feugiat. Nam ullamcorper tempor fringilla. Morbi posuere tortor sit amet augue gravida ut malesuada dui tincidunt. Nunc sodales ipsum eget ante feugiat nec ultrices ante rutrum. Vestibulum nisl nisi, elementum a imperdiet quis, cursus a libero. Ut vel lacus lacus. Praesent sed mauris neque, vel laoreet purus. Proin sit amet luctus orci. Mauris consectetur convallis euismod. Curabitur sodales vestibulum lobortis.\n" + 
  		"\n" + 
  		"Curabitur pulvinar urna ut libero dignissim aliquet. Aliquam vitae velit lacus. Pellentesque malesuada tristique eros, ut varius risus dignissim eu. Quisque nec urna eu turpis fermentum placerat id vitae lorem. Vivamus hendrerit fringilla ipsum, vitae sagittis erat lobortis non. Morbi dictum euismod quam vitae iaculis. Phasellus in elit nec dui vehicula tristique eget eget augue. Fusce bibendum, ligula vel rhoncus viverra, lectus orci rhoncus odio, vitae sodales lorem massa in odio. Sed eget ante enim. Nunc a libero ante, eget rutrum felis. Nulla elit sapien, consequat vel pretium quis, sollicitudin eget diam. Sed nisi dolor, imperdiet et gravida sit amet, ultricies sit amet turpis.\n" + 
  		"\n" + 
  		"Etiam eget tortor lacus, eu mollis felis. Cras commodo ligula ac nisi pretium cursus. Nulla blandit sapien non ante facilisis sit amet venenatis turpis dignissim. Nulla lorem est, bibendum et fringilla sed, consequat lacinia felis. Vestibulum commodo, est nec interdum pretium, dui risus malesuada mauris, in vestibulum elit mi quis mauris. Nam convallis pellentesque risus, et semper purus lacinia vitae. Pellentesque at pretium nisi. Mauris libero dui, blandit in vulputate vehicula, mollis nec nunc. Suspendisse volutpat, enim sed venenatis ultricies, erat dui faucibus urna, sed convallis augue metus sed metus.\n" + 
  		"\n" + 
  		"Aenean faucibus lacinia tellus sed mattis. Aliquam in dictum justo. Nunc sit amet mauris mauris. Pellentesque mattis dolor non neque dignissim porta. Nunc varius nisi consequat arcu gravida eu sodales eros volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sed odio sapien, vel vestibulum tellus. Fusce eleifend, nisl non convallis egestas, ligula dui adipiscing lacus, dictum porttitor nisl leo ac velit. Nullam rutrum odio ut elit euismod viverra. Suspendisse potenti. Nunc aliquam luctus vulputate. Nam rhoncus convallis tempus.\n" + 
  		"\n" + 
  		"Integer fringilla enim tincidunt urna porttitor posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sodales est ut ipsum sagittis sodales. Maecenas mattis tincidunt libero at pretium. Vivamus dapibus orci eget neque porttitor viverra. Quisque semper elit at libero venenatis eu egestas tortor suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec nec felis tortor. Duis eleifend, nulla non luctus aliquet, enim est volutpat lorem, sed sollicitudin libero leo non risus. Etiam ut viverra erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam dignissim viverra dolor sed vulputate. Mauris ipsum arcu, sollicitudin eget hendrerit eget, semper quis sem.\n" + 
  		"\n" + 
  		"Curabitur lectus lorem, lacinia id aliquam auctor, interdum ac elit. Ut massa augue, vulputate sit amet dignissim et, rhoncus in est. In hac habitasse platea dictumst. Nulla tincidunt sagittis massa in gravida. Aliquam justo eros, accumsan sit amet mollis sed, posuere venenatis ipsum. Fusce libero nisi, commodo vitae dictum nec, blandit vel turpis. Duis felis urna, imperdiet non cursus in, tincidunt nec mi.\n" + 
  		"\n" + 
  		"Donec et nisl tortor. Nunc iaculis rutrum lectus, at convallis enim malesuada vitae. Aliquam sit amet ante elit. Nam quis bibendum lacus. Quisque in sem mauris. Cras quis sagittis ipsum. Praesent et dolor quis elit vehicula cursus eu sollicitudin est. In quis dui sapien. Donec lacinia mattis scelerisque. Aenean non turpis leo. Suspendisse porttitor tempor sapien, sed gravida nisl varius ut. Proin tempor consequat elit, nec volutpat orci fermentum id. Maecenas quis nisl a magna pellentesque elementum non a massa.\n" + 
  		"\n" + 
  		"Pellentesque vel orci sed justo adipiscing aliquam. Sed aliquet varius aliquet. Nam neque arcu, dapibus eu tempor id, lobortis ut dui. Pellentesque a tellus nibh, ac facilisis justo. Fusce varius interdum ornare. Quisque quis mi ut est aliquam facilisis ac in eros. Sed dignissim tincidunt elementum. Nam et nibh eu augue condimentum adipiscing sit amet in erat. Phasellus sed tempus ipsum. Sed vel dapibus nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis tempus elementum adipiscing. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sodales metus eget enim mollis facilisis. Morbi in erat nulla.\n" + 
  		"\n" + 
  		"Etiam eu tellus in neque luctus commodo a laoreet dui. Fusce at dui massa, vel vestibulum metus. Phasellus et risus lacus, ut laoreet mauris. Cras tempus suscipit nulla at egestas. Ut consequat feugiat odio, sed varius ante commodo ac. Ut enim orci, rhoncus in pulvinar eget, posuere non libero. Quisque a aliquet enim. Quisque ac ligula at nulla placerat gravida vel sit amet massa. Vivamus ornare tempus massa, eu bibendum quam tempor a.\n" + 
  		"\n" + 
  		"Donec nec lacus sit amet urna fringilla semper. Duis vestibulum dapibus accumsan. Vestibulum vestibulum adipiscing porta. Maecenas tempus enim a nunc ultricies tristique. Etiam blandit, felis eget pretium ullamcorper, enim enim tempus odio, id adipiscing ligula dui at purus. Suspendisse egestas mollis diam vel dignissim. Maecenas hendrerit justo et sapien posuere accumsan. Nunc gravida, ligula quis interdum viverra, enim urna facilisis sapien, vitae congue lorem justo eu eros. Sed euismod sem eget purus gravida varius. Mauris ultrices, lorem tincidunt lobortis feugiat, orci neque pellentesque ligula, eget mattis dui nisl vitae lacus.\n" + 
  		"\n" + 
  		"Nullam mi nisl, auctor volutpat tristique tempus, lacinia et felis. Etiam pretium, arcu non semper vehicula, mauris lorem bibendum mauris, nec viverra purus magna ut turpis. Nullam vel nunc at erat iaculis suscipit a sit amet turpis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac enim a ipsum tristique elementum suscipit in sem. Duis egestas dignissim turpis, a ornare nunc porttitor in. Cras fermentum dignissim metus, sit amet accumsan mi tristique non. Phasellus lorem mauris, dapibus ac tincidunt ut, pulvinar tincidunt mi.\n" + 
  		"\n" + 
  		"Sed lacus enim, euismod vitae suscipit ac, malesuada mollis nibh. Proin vel aliquam orci. Vestibulum commodo laoreet purus, id faucibus nulla rhoncus at. Aliquam nec dui nec neque ornare gravida sit amet a augue. Integer rhoncus, nunc eget blandit lacinia, libero diam volutpat lacus, a venenatis enim lacus vestibulum orci. Morbi egestas condimentum sagittis. Mauris at tellus metus. Quisque nec mi eros.\n" + 
  		"\n" + 
  		"Proin sit amet mi metus, at accumsan quam. In rhoncus, augue ut dictum molestie, arcu nisl venenatis quam, a sodales tellus arcu nec ante. Praesent consequat aliquet consequat. Nunc ac sodales lectus. Nunc sit amet tincidunt augue. Etiam turpis arcu, fringilla eu consequat eget, sollicitudin eget nisi. Nam tincidunt viverra sem, id faucibus lacus sagittis quis. Phasellus facilisis suscipit felis eu vehicula. Proin ut urna odio. Ut justo libero, aliquet at imperdiet quis, congue non nunc. Vivamus varius molestie massa, id elementum nibh porta ac.\n" + 
  		"\n" + 
  		"Quisque volutpat auctor ante, sit amet mollis dui varius in. Nunc sed diam libero. Aliquam hendrerit molestie ornare. Nam venenatis posuere faucibus. Morbi aliquet sollicitudin urna, nec consequat mi varius sit amet. Morbi quam diam, faucibus sed ultricies pretium, varius eu velit. Vivamus leo urna, ultrices a dignissim at, interdum pharetra dolor. In hac habitasse platea dictumst. Ut hendrerit lectus eu sem suscipit semper.\n" + 
  		"\n" + 
  		"Duis vel justo quam, a semper nisi. Mauris lacus nunc, consequat non volutpat non, elementum vitae tortor. Sed id justo turpis. Morbi est massa, mollis eget rutrum id, posuere in tellus. Mauris accumsan urna id orci pretium imperdiet. Donec bibendum, libero sed placerat commodo, sapien massa consectetur metus, quis elementum eros justo sit amet tortor. Pellentesque condimentum accumsan luctus. Duis justo ante, vehicula id pellentesque ac, gravida ac justo. Donec fermentum, ante sit amet condimentum commodo, orci ante scelerisque ante, sit amet porttitor nulla ante nec libero. Sed nisl odio, ullamcorper vitae venenatis ut, aliquet vel quam. Curabitur et mi arcu. Suspendisse ac tellus elit, in feugiat nisl. Donec vel dui quis turpis feugiat vestibulum in ut orci. Proin sed eros at leo pellentesque interdum. Praesent fringilla ultricies fringilla.\n" + 
  		"\n" + 
  		"Nunc est mauris, interdum laoreet congue ut, condimentum quis nisi. Pellentesque in interdum nibh. Suspendisse potenti. Suspendisse ullamcorper cursus augue eget consequat. Nam pulvinar, arcu eleifend aliquam condimentum, nisl tortor scelerisque nibh, in tempor mi lectus a tellus. Donec ac nisl eget risus fermentum adipiscing venenatis et libero. Nulla a magna at odio scelerisque adipiscing et in urna.\n" + 
  		"\n" + 
  		"Maecenas venenatis, libero vitae rutrum vulputate, est nulla venenatis metus, quis sodales magna turpis quis arcu. Phasellus sed mollis lacus. Nam eleifend sagittis felis eget sollicitudin. Ut nibh purus, fringilla et dignissim eget, pharetra sit amet odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer lacinia nisl ac tellus imperdiet tincidunt. Curabitur egestas faucibus nulla eget consequat. In adipiscing, elit in ullamcorper facilisis, nulla nulla consequat leo, eu tristique nulla augue non mi. Nullam nec iaculis lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pretium lobortis hendrerit. Nulla facilisi.\n" + 
  		"\n" + 
  		"Vestibulum malesuada, lectus non blandit tincidunt, leo orci venenatis nisl, id interdum leo mauris vulputate felis. Vestibulum at justo id quam placerat consequat vitae quis justo. Praesent ornare nisi non elit euismod in venenatis nibh tristique. Sed ac lectus eu urna dapibus egestas. Donec commodo, nulla sit amet tincidunt dignissim, nulla mauris bibendum diam, et fringilla ligula urna at odio. Quisque vitae sem massa, quis vehicula eros. Aenean eu lectus mauris, eget convallis magna. Duis laoreet dolor vel nisi tempus malesuada. Quisque posuere ornare consequat. Vivamus lacinia mattis velit, ac molestie leo facilisis sit amet. Praesent eget dui justo, in semper purus. Vestibulum malesuada ipsum euismod neque pretium vitae tincidunt nulla eleifend. Nulla nec elit et leo tincidunt faucibus nec vel quam. Sed felis tortor, posuere in accumsan nec, tempor placerat metus.\n" + 
  		"\n" + 
  		"Curabitur mattis odio et massa mollis sed mattis orci scelerisque. Aenean non ultricies ipsum. Fusce erat ante, elementum a pharetra a, mattis ac massa. Mauris sagittis nunc vitae felis interdum non hendrerit tellus pharetra. Nam quis dolor et urna accumsan imperdiet ut quis orci. Integer massa ante, vulputate vel euismod non, mollis in enim. In odio risus, vestibulum a cursus nec, ultrices vel orci. Aliquam erat volutpat. In hac habitasse platea dictumst. Proin rutrum, ante id porta congue, est lorem elementum enim, in vehicula enim orci eget massa.\n" + 
  		"\n" + 
  		"Suspendisse vulputate rhoncus enim vel vehicula. Cras at pretium tortor. Suspendisse nec tellus tortor, quis congue justo. Nulla ligula lorem, condimentum eu tincidunt at, ultricies id enim. Mauris congue rutrum pharetra. Donec tortor dolor, fringilla at rhoncus ut, posuere sit amet leo. Donec hendrerit velit et orci imperdiet non interdum elit pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent egestas mollis arcu, sit amet feugiat mauris placerat sed.\n" + 
  		"\n" + 
  		"Nam porttitor rhoncus nisl adipiscing faucibus. Integer sed pharetra metus. Nam at velit quam, vestibulum bibendum arcu. Fusce luctus tempor mi, et lobortis dolor vestibulum quis. In vel mi justo. Duis hendrerit metus sed tortor tincidunt vel vehicula justo sagittis. Aenean sit amet dolor at risus fermentum condimentum eu at diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n" + 
  		"\n" + 
  		"Curabitur tempus vestibulum elit, ac euismod lacus bibendum sit amet. Donec erat metus, viverra nec laoreet laoreet, pellentesque at libero. Praesent pharetra venenatis ipsum, at sodales arcu posuere id. Mauris eget vulputate urna. Ut blandit felis eu mauris vulputate convallis. Etiam sagittis, mauris id scelerisque dictum, diam neque placerat quam, nec malesuada sapien mauris nec lectus. Morbi ut vehicula odio. In condimentum augue et nibh pulvinar auctor. Fusce fringilla gravida pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies adipiscing felis vitae congue. Ut orci urna, fermentum sit amet aliquam ut, sagittis in est. In aliquet justo fringilla augue tempus non tristique magna convallis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed a porta tellus.\n" + 
  		"\n" + 
  		"Sed rhoncus, sapien in bibendum porttitor, felis dolor venenatis leo, at blandit neque tortor vitae tortor. Sed enim neque, tristique at iaculis vitae, ornare nec risus. Praesent viverra pulvinar sem a dignissim. Sed at tempor dui. Curabitur ipsum nisi, laoreet a consequat nec, gravida at odio. Curabitur accumsan, enim non volutpat dictum, turpis ante fermentum ipsum, non dictum justo enim quis arcu. Aliquam massa massa, pharetra a euismod eget, tincidunt vel eros. Nullam facilisis nulla eget risus dapibus ac feugiat ipsum lobortis. Etiam vestibulum aliquam orci, non tempor augue feugiat nec. Vivamus vitae nibh molestie ipsum scelerisque ornare. Aenean sodales lorem eget dolor elementum tempus. Proin et sem et erat tincidunt mattis sit amet at turpis. Ut fringilla congue justo a luctus. Fusce sed tellus at turpis pulvinar sodales.\n" + 
  		"\n" + 
  		"Mauris eleifend consequat imperdiet. Sed et diam ipsum, sed suscipit metus. Vestibulum et lacus quis nunc mattis tincidunt eget eu mauris. Nunc elementum, mi sit amet rutrum porta, urna metus elementum neque, sit amet commodo lacus augue et sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla erat tortor, posuere nec tincidunt ut, scelerisque sit amet magna. Ut sit amet diam amet.\n" + 
  		"\n" + 
  		"";

  private static final String EMPTY_STRING = "";

  // test an empty string
  public void testStreamEmpty() {
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    Streamer.stream(new ByteArrayInputStream(EMPTY_STRING.getBytes()),
        outputStream);
    String result = outputStream.toString();
    assertEquals(EMPTY_STRING, result);
  }

  // test a short string
  public void testStreamShort() {
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    Streamer.stream(new ByteArrayInputStream(TEST_SHORT.getBytes()),
        outputStream);
    String result = outputStream.toString();
    assertEquals(TEST_SHORT, result);
  }

  // test a long string
  public void testStreamLong() {
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    Streamer.stream(new ByteArrayInputStream(TEST_LONG.getBytes()),
        outputStream);
    String result = outputStream.toString();
    assertEquals(TEST_LONG, result);
  }

}
